"""
Django settings for iTrade4Phones project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from urllib.parse import quote_plus
import os
import time
import math
from django.core.exceptions import ImproperlyConfigured
#import dj_database_url
#from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-akm20$dm2)7761z*%f+()4capwak^*rjix^am@mx1q&&gee!j#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['itrade-backend.onrender.com', '127.0.0.1', 'api.itrade4phones.com', 'itrade4phonesbackend-271nacdm.b4a.run', '.vercel.app']


# Application definition

INSTALLED_APPS = [
    'store',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'store.middleware.VisitTrackingMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'iTrade4Phones.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # This should be present
]

WSGI_APPLICATION = 'iTrade4Phones.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases


# settings.py



def get_env_variable(var_name, default=None):
    """Get environment variable or return exception."""
    try:
        return os.environ[var_name]
    except KeyError:
        if default is not None:
            return default
        error_msg = f"Set the {var_name} environment variable"
        raise ImproperlyConfigured(error_msg)

# Base database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_env_variable('DB_NAME'),
        'USER': get_env_variable('DB_USER'),
        'PASSWORD': get_env_variable('DB_PASSWORD'),
        'HOST': get_env_variable('DB_HOST'),
        'PORT': get_env_variable('DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
            'connect_timeout': 5,
            'options': '-c search_path=public -c statement_timeout=5000',
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
        'CONN_MAX_AGE': 600,  # 10 minutes connection persistence
        'DISABLE_SERVER_SIDE_CURSORS': False,  # For large query sets
    }
}

# Production-specific enhancements
if not DEBUG:
    # Connection pool configuration
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True
    DATABASES['default']['ATOMIC_REQUESTS'] = True  # Wrap web requests in transactions
    
    # Additional production optimizations
    DATABASES['default']['OPTIONS'].update({
        'connect_timeout': 3,  # Shorter timeout for production
        'application_name': 'iTrade4Phones',
    })

    # Read replica configuration (if available)
    if 'DB_REPLICA_HOST' in os.environ:
        DATABASES['replica'] = {
            **DATABASES['default'],
            'HOST': get_env_variable('DB_REPLICA_HOST'),
            'PORT': get_env_variable('DB_REPLICA_PORT', DATABASES['default']['PORT']),
            'USER': get_env_variable('DB_REPLICA_USER', DATABASES['default']['USER']),
            'PASSWORD': get_env_variable('DB_REPLICA_PASSWORD', DATABASES['default']['PASSWORD']),
            'TEST': {'MIRROR': 'default'},
        }

'''DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}'''

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ]
}

CORS_ALLOWED_ORIGINS = ["http://localhost:5173", "https://i-trade-frontend.vercel.app", "https://itrade4phones.com", "https://www.itrade4phones.com"]
CORS_ALLOW_CREDENTIALS = True

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # True in production with HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = False  # True in production with HTTPS

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CSRF_TRUSTED_ORIGINS = [
    "https://www.itrade4phones.com",
    "https://api.itrade4phones.com", 
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


def get_bool_env(env_var: str, default: bool = False) -> bool:
    """Safely parse boolean environment variables."""
    val = os.getenv(env_var, "")
    if not val:
        return default
    return val.lower() in ("true", "1", "t", "y", "yes")

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'store.resend_backend.ResendBackend')  # Fallback for development
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')  # You can change this after domain verification

# Helper functions
def to_int_seconds(td):
    """Safely convert timedelta to integer seconds"""
    return int(math.floor(td.total_seconds()))

def get_bool_env(env_var, default=False):
    """Parse boolean environment variables"""
    val = os.getenv(env_var, "")
    return val.lower() in ("true", "1", "t", "y", "yes") if val else default

# Redis Configuration
REDIS_CONFIG = {
    'PASSWORD': os.getenv('REDIS_PASSWORD'),
    'HOST': os.getenv('REDIS_HOST'),
    'PORT': os.getenv('REDIS_PORT'),
    'DB': os.getenv('REDIS_DB'),
    'SSL': get_bool_env('REDIS_SSL'),
    'TIMEOUT': 5
}

# Build Redis URL with proper encoding
REDIS_SCHEME = "rediss" if REDIS_CONFIG['SSL'] else "redis"
REDIS_URL = f"{REDIS_SCHEME}://:{quote_plus(REDIS_CONFIG['PASSWORD'])}@{REDIS_CONFIG['HOST']}:{REDIS_CONFIG['PORT']}/{REDIS_CONFIG['DB']}"

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    },
    "redis": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": REDIS_CONFIG['TIMEOUT'],
            "SOCKET_TIMEOUT": REDIS_CONFIG['TIMEOUT'],
            "CONNECTION_POOL_KWARGS": {
                "ssl_cert_reqs": None,
                "max_connections": 100,
                "retry_on_timeout": True,
                "health_check_interval": 30,
                "socket_keepalive": True
            },
            "IGNORE_EXCEPTIONS": True,  # Critical for production
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
        },
        "KEY_PREFIX": "itrade_prod",
        "TIMEOUT": to_int_seconds(timedelta(days=1)),
    }
}

# Cache Versioning
CACHE_VERSION = int(os.getenv('CACHE_VERSION', str(int(time.time()))))
def get_cache_version():
    from django.core.cache import cache
    version = cache.get("global_cache_version", CACHE_VERSION)
    return version

# Cache TTL Configuration
CACHE_TTLS = {
    'phone_list': to_int_seconds(timedelta(minutes=30)),
    'phone_detail': to_int_seconds(timedelta(hours=2)),
    'featured_phones': to_int_seconds(timedelta(minutes=10)),
    'variant_data': to_int_seconds(timedelta(days=1)),
    'session': to_int_seconds(timedelta(weeks=2)),
}

# Session Configuration - Using DB for reliability
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = CACHE_TTLS['session']

# Monitoring
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
DJANGO_REDIS_LOGGER = 'django.redis'

# Health Check
def redis_health_check():
    try:
        import redis
        r = redis.Redis(
            host=REDIS_CONFIG['HOST'],
            port=int(REDIS_CONFIG['PORT']),
            password=REDIS_CONFIG['PASSWORD'],
            ssl=REDIS_CONFIG['SSL'],
            socket_connect_timeout=3
        )
        return r.ping()
    except Exception as e:
        return False

if not DEBUG and not redis_health_check():
    print("Warning: Redis connection failed - using local memory cache")
    CACHES['default'] = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "fallback",
    }

PAYSTACK_PUBLIC_KEY = os.getenv('PAYSTACK_PUBLIC_KEY')
PAYSTACK_SECRET_KEY = os.getenv('PAYSTACK_SECRET_KEY')
PAYSTACK_SECRET_TEST = os.getenv('PAYSTACK_SECRET_TEST')
